"""Create tables

Revision ID: f7bd20fcec19
Revises: 
Create Date: 2024-03-03 01:45:53.855944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7bd20fcec19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('name_user', sa.String(), nullable=False),
            sa.Column('email_user', sa.String(), nullable=False),
            sa.Column('password', sa.String(length=35), nullable=False),
            sa.Column('date_reg', sa.DATE(), nullable=False),
            sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('recipe',
    sa.Column('id_recipe', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('title_recipe', sa.String(), nullable=False),
            sa.Column('description', sa.String(), nullable=False),
            sa.Column('complexity', sa.String(), nullable=False),
            sa.Column('time_cook', sa.Integer(), nullable=False),
            sa.Column('date_create', sa.DATE(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
            sa.PrimaryKeyConstraint('id_recipe')
    )
    op.create_table('photorecipe',
    sa.Column('id_photorec', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('recipe_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id_recipe'], ),
            sa.PrimaryKeyConstraint('id_photorec')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photorecipe')
    op.drop_table('recipe')
    op.drop_table('user')
    # ### end Alembic commands ###
